name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Actualiza a una versión de Node.js compatible

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest  # Usa npx para ejecutar Jest
        env:
          CI: true
